### ISSUE TITLE
Peer feeback (1) Reinier van Limpt

### ISSUE THREAD

**Issue by ReiniervanLimpt** [gijslaarman/web-app-from-scratch-1920#2]
Very complex routing, nice! it looks like you created a good base and structure before making calls to the api.

Fetching data has been commented out, this piece of code is very comprehensible for me and doesnt make use of the modules you wrote making me think you split up your functionality very well.

I will try to give feedback on your routing when i have actually covered the subject myself ;)

**Comment by gijslaarman** [comment]
Thanks m8!
