### ISSUE TITLE
innerHtml vs removing all children

### ISSUE THREAD

**Issue by aaraar** [gijslaarman/web-app-from-scratch-1920#3]
https://github.com/gijslaarman/web-app-from-scratch-1920/blob/09070fe38cc24138c722b3905092f5a58a9757d3/docs/js/modules/renderpage.mjs#L21

For cross browser support, security and stability issues I recommend using a function and/or loop to remove all children from a container instead of assigning an empty string to innerHtml

Example:
```js
while (element.firstChild) element.removeChild(element.firstChild);
```

**Comment by gijslaarman** [comment]
Definitely better! Will implement soon

**Comment by gijslaarman** [comment]
Done! ✌️
