### ISSUE TITLE
Why use a 'let' here

### ISSUE THREAD

**Issue by joostf** [gijslaarman/web-app-from-scratch-1920#5]
https://github.com/gijslaarman/web-app-from-scratch-1920/blob/09070fe38cc24138c722b3905092f5a58a9757d3/docs/js/modules/router.mjs#L31

**Comment by gijslaarman** [comment]
I wanted to change the urlHash with some minor fallbacks. To make the page more accessible.
E.g: if a user entered `https://host.com/#teams` it would automatically recognize it as `#/teams`. So that the user is allowed to make some errors in the link.
